---
substitutions:
  id_prefix: ratgdov2
  friendly_name: "RATGDOv2"
  uart_tx_pin: "16"
  uart_rx_pin: "33"
  input_obst_pin: "11"
  status_door_pin: "5"
  status_obstruction_pin: "12"
  dry_contact_open_pin: "7"
  dry_contact_close_pin: "9"
  dry_contact_light_pin: "18"

web_server:

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ratgdo.v2board_esp32_lolin_s2_mini
    version: "2.0"

esp32:
  variant: esp32s2
  framework:
    type: arduino

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v2board_esp32_lolin_s2_mini.yaml@main

packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server

improv_serial:

wifi:
  ap:

logger:
