---
substitutions:
  id_prefix: ratgdov2
  friendly_name: "ratgdov2"
  uart_tx_pin: D4
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

web_server:

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ratgdo.esphome
    version: "2.0"

esp8266:
  board: d1_mini_lite
  restore_from_flash: true

dashboard_import:
  package_import_url: github://esphome-ratgdo/esphome-ratgdo/v2board_esp8266_d1_mini_lite.yaml@main

packages:
  remote_package:
    url: https://github.com/esphome-ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s
    ref: enums_refactor

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server

ota:

improv_serial:

wifi:
  ap:

logger:
